package com.vince.andframe.base.database.dbgen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vince.andframe.base.database.PrivateStorage;

import com.vince.andframe.base.database.dbgen.PrivateStorageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig privateStorageDaoConfig;

    private final PrivateStorageDao privateStorageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        privateStorageDaoConfig = daoConfigMap.get(PrivateStorageDao.class).clone();
        privateStorageDaoConfig.initIdentityScope(type);

        privateStorageDao = new PrivateStorageDao(privateStorageDaoConfig, this);

        registerDao(PrivateStorage.class, privateStorageDao);
    }
    
    public void clear() {
        privateStorageDaoConfig.clearIdentityScope();
    }

    public PrivateStorageDao getPrivateStorageDao() {
        return privateStorageDao;
    }

}
